# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=debug
      #- CORE_LOGGING_PEER=info
      - CORE_LOGGING_CAUTHDSL=warning
      - CORE_LOGGING_GOSSIP=warning
      - CORE_LOGGING_LEDGER=debug
      - CORE_LOGGING_MSP=warning
      - CORE_LOGGING_POLICIES=warning
      - CORE_LOGGING_GRPC=error
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      #- CORE_PEER_GOSSIP_PULLINTERVAL=500s
      #- CORE_PEER_GOSSIP_REQUESTSTATEINFOINTERVAL=120s
      #- CORE_PEER_GOSSIP_PUBLISHSTATEINFOINTERVAL=130s
      #- CORE_PEER_GOSSIP_STATEINFORETENTIONINTERVAL=500s
      #- CORE_PEER_GOSSIP_PUBLISHCERTPERIOD=500s
      #- CORE_PEER_GOSSIP_ALIVETIMEINTERVAL=500s
      #- CORE_PEER_GOSSIP_ALIVEEXPIRATIONTIMEOUT=600s
      #- CORE_PEER_GOSSIP_ELECTION_LEADERELECTIONDURATION=60s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /bin:/bin
      - /sbin:/sbin
    command: peer node start
