apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ca1.byfn-solo
  name: ca1
spec:
  clusterIP: 192.168.195.81
  ports:
  - name: "7054"
    port: 7054
    targetPort: 7054
  selector:
    io.kompose.service: ca1.byfn-solo
status:
  loadBalancer: {}
