apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ca2.byfn-solo
  name: ca2
spec:
  clusterIP: 192.168.195.82
  ports:
  - name: "7054"
    port: 7054
    targetPort: 7054
  selector:
    io.kompose.service: ca2.byfn-solo
status:
  loadBalancer: {}
