apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cli
  name: cli
spec:
  clusterIP: 192.168.195.90 
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: cli
status:
  loadBalancer: {}
