apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: orderer.byfn-solo
  name: orderer
spec:
  clusterIP: 192.168.195.70
  ports:
  - name: "7050"
    port: 7050
    targetPort: 7050
  selector:
    io.kompose.service: orderer.byfn-solo
status:
  loadBalancer: {}
