apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer1.org1.byfn-solo
  name: peer1-org1
spec:
  clusterIP: 192.168.195.11
  ports:
  - name: "8051"
    port: 8051
    targetPort: 7051
  - name: "8053"
    port: 8053
    targetPort: 7053
  selector:
    io.kompose.service: peer1.org1.byfn-solo
status:
  loadBalancer: {}
