apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer1.org2.byfn-solo
  name: peer1-org2
spec:
  clusterIP: 192.168.195.21
  ports:
  - name: "10051"
    port: 10051
    targetPort: 7051
  - name: "10053"
    port: 10053
    targetPort: 7053
  selector:
    io.kompose.service: peer1.org2.byfn-solo
status:
  loadBalancer: {}
