apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.org1.byfn-solo
  name: peer0-org1
spec:
  clusterIP: 192.168.195.10
  ports:
  - name: "7051"
    port: 7051
    targetPort: 7051
  - name: "7053"
    port: 7053
    targetPort: 7053
  selector:
    io.kompose.service: peer0.org1.byfn-solo
status:
  loadBalancer: {}
