apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.org2.byfn-solo
  name: peer0-org2
spec:
  clusterIP: 192.168.195.20
  ports:
  - name: "9051"
    port: 9051
    targetPort: 7051
  - name: "9053"
    port: 9053
    targetPort: 7053
  selector:
    io.kompose.service: peer0.org2.byfn-solo
status:
  loadBalancer: {}
